kind: Service
apiVersion: v1
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
  - port: 90
    targetPort: 8000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmindiola-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: springboot
          image: inventory/springboot
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP